### ISSUE TITLE
Feature Request: Support parsing of pre-fetched html

### ISSUE THREAD

**Issue by DerGut** [postlight/mercury-parser#277]
I have some html pages in my database and would like to parse them instead of re-downloading them. Is there an easy way to pass the html directly to the mercury-parser?

**Comment by benubois** [comment]
I think this is [already possible](https://github.com/postlight/mercury-parser/blob/b044cfa958014beae03c6f69a3b32499abe765af/src/mercury.js#L12), for example:

```javascript
const html = `<html>
<body></body>
</html>`;

Mercury.parse("http://example.com", { html });
```

**Comment by adampash** [comment]
That's 100% correct! Thanks @benubois

**Comment by DerGut** [comment]
Thanks for your quick replies!

However, when I run this I get the below exception. My html is a string and even passing `Buffer.from(html)` doesn't help.

```
(node:6) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "buf" argument must be one of type Buffer, TypedArray, or DataView. Received type object
    at InternalDecoder.write (string_decoder.js:74:11)
    at StripBOMWrapper.write (/node_modules/@postlight/mercury-parser/node_modules/iconv-lite/lib/bom-handling.js:35:28)
    at Object.decode (/node_modules/@postlight/mercury-parser/node_modules/iconv-lite/lib/index.js:42:23)
    at Object.encodeDoc (/node_modules/@postlight/mercury-parser/dist/mercury.js:1700:32)
    at Object.generateDoc (/node_modules/@postlight/mercury-parser/dist/mercury.js:1682:18)
    at Object._callee$ (/node_modules/@postlight/mercury-parser/dist/mercury.js:1656:53)
    at tryCatch (/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:5:24)
```

**Comment by adampash** [comment]
@DerGut Can you provide some sample code reproducing this? 

Also what version of Mercury are you using?

**Comment by DerGut** [comment]
This is the code causing the exception:

```
const express = require('express');
const Mercury = require('@postlight/mercury-parser');

const app = express();
app.post('/', (req, res) => {
	console.log('Received request', req.body);
	
	Mercury.parse("https://mercury.postlight.com", {
		html: "<html><body>just testing</body></html>"
	}).then(result => console.log(result));
});

const server = app.listen(8080, function() {
	var host = server.address().address;
	var port = server.address().port;
	console.log(`Running on http://${host}:${port}`);
});
```

I am using it in a docker container with the following Dockerfile:

```
FROM node:latest

RUN yarn add \
	express \
	@postlight/mercury-parser
COPY app.js .

EXPOSE 8080

CMD ["node", "app.js"]
```

I haven't set the mercury version explicitly but the generated `package.json` and `yarn.lock` files both indicate version 1.1.1

**Comment by DerGut** [comment]
I just found the breaking change #260. Sorry for the trouble guys, I got it now working!
