### ISSUE TITLE
Error: Request path contains unescaped characters

### ISSUE THREAD

**Issue by NightMachinary** [postlight/mercury-parser#392]
- **Platform**: Linux server 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 GNU/Linux
- **Mercury Parser Version**: —version doesn’t work but very recent install 
- **Node Version v11.10.0

mercury-parser 'https://en.m.wikipedia.org/wiki/Tf–idf'

Mercury Parser encountered a problem trying to parse that resource.

TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:127:13)
    at Object.request (https.js:303:10)
    at Request.start (/home/linuxbrew/.linuxbrew/lib/node_modules/@postlight/mercury-parser/node_modules/postman-request/request.js:865:32)
    at Request.end (/home/linuxbrew/.linuxbrew/lib/node_modules/@postlight/mercury-parser/node_modules/postman-request/request.js:1736:10)
    at end (/home/linuxbrew/.linuxbrew/lib/node_modules/@postlight/mercury-parser/node_modules/postman-request/request.js:643:14)
    at Immediate.<anonymous> (/home/linuxbrew/.linuxbrew/lib/node_modules/@postlight/mercury-parser/node_modules/postman-request/request.js:657:7)
    at processImmediate (timers.js:637:19)

**Comment by toufic-m** [comment]
In such cases, the special characters in the URL need to be encoded and passed to Mercury Parser in the same format as they would be if copied from a browser's URL bar. This URL, for example, would need to be passed as: https://en.m.wikipedia.org/wiki/Tf%E2%80%93idf

**Comment by NightMachinary** [comment]
@toufic-m Thanks! I copied the url from iOS Safari, which didn’t do this. Is there an open source tool to automatically do this?

**Comment by NightMachinary** [comment]
I tried this:
```
tlrl "$(echo https://en.m.wikipedia.org/wiki/Tf–idf | xxd -plain | tr -d '\n' | sed 's/\(..\)/%\1/g')"
Error: ErrorMessage { msg: "Error deserializing mercury api response json: missing field `title` at line 4 column 1" }
```

And it doesn’t work but the error has changed. :))

**Comment by NightMachinary** [comment]
I have found  https://github.com/seomoz/url-py/ to do this job, but somehow it doesn’t install for me. Anyhow, I think this url encoding thing should be automated in mercury-parser.

**Comment by chathuriw** [comment]
We are also having a similar issue. We want to parse a url like 'https://www.dcclothesline.com/2019/05/08/trump-to-redefine-poverty-eliminate-americans-from-welfare/*****TRUMP/' which gives the below error. 

`(node:794) UnhandledPromiseRejectionWarning: SyntaxError: Invalid regular expression: /^https://www.dcclothesline.com/2019/05/08/trump-to-redefine-poverty-eliminate-americans-from-welfare/*****TRUMP/: Nothing to repeat
    at new RegExp (<anonymous>)
    at makeBaseRegex (/nfs/nfs7/home/truthy/node_modules/@postlight/mercury-parser/dist/mercury.js:6229:10)
    at scoreLinks (/nfs/nfs7/home/truthy/node_modules/@postlight/mercury-parser/dist/mercury.js:6245:19)
    at Object.extract [as next_page_url] (/nfs/nfs7/home/truthy/node_modules/@postlight/mercury-parser/dist/mercury.js:6311:23)
    at Object.extract (/nfs/nfs7/home/truthy/node_modules/@postlight/mercury-parser/dist/mercury.js:6455:30)
    at Object.extract (/nfs/nfs7/home/truthy/node_modules/@postlight/mercury-parser/dist/mercury.js:6704:52)
    at Object._callee$ (/nfs/nfs7/home/truthy/node_modules/@postlight/mercury-parser/dist/mercury.js:6958:38)
    at tryCatch (/nfs/nfs7/home/truthy/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/nfs/nfs7/home/truthy/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (/nfs/nfs7/home/truthy/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/nfs/nfs7/home/truthy/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:5:24)
    at _next (/nfs/nfs7/home/truthy/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:27:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:794) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:794) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
b''
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    valid_json = demjson.decode(mercury_parse)
  File "/u/truthy/miniconda3/envs/hoaxy-be-py3/lib/python3.7/site-packages/demjson.py", line 5699, in decode
    return_stats=(return_stats or write_stats) )
  File "/u/truthy/miniconda3/envs/hoaxy-be-py3/lib/python3.7/site-packages/demjson.py", line 4915, in decode
    raise errors[0]
`  
And if I escape the special characters, it gives the below error. 
`{ error: true,\n  message:\n   'The url parameter passed does not look like a valid URL. Please check your URL and try again.' }\n"
{"error": true, "message": "The url parameter passed does not look like a valid URL. Please check your URL and try again."}`

**Comment by NightMachinary** [comment]
The original case of https://en.m.wikipedia.org/wiki/Tf-idf now doesn't produce an error. 

Also,If anyone is interested, I have created this little script to encode the urls, and it seems to work:
```
#!/usr/bin/env python3
import fileinput
import urllib.parse

for line in fileinput.input():
    print(urllib.parse.quote(line.rstrip(), safe='/:?=&'))
```
