### ISSUE TITLE
yarn generate-parser errors on empty srcset

### ISSUE THREAD

**Issue by Meandmybadself** [postlight/mercury-parser#497]
- **Platform**: MacOS Mojave
- **Mercury Parser Version**: master
- **Node Version (if a Node bug)**: v8.10.0
- **Browser Version (if a browser bug)**: n/a

## Expected Behavior

Invoking `yarn generate-parser` should ideally generate a parser.

## Current Behavior

In the event that an image has an empty/spaces _srcset_ attribute, the process exits with an error.

## Steps to Reproduce

1. Install `mercury-client` as explained at https://github.com/postlight/mercury-parser/blob/master/src/extractors/custom/README.md#how-to-generate-a-custom-parser
2. `yarn generate-parser`
3. When prompted for a URL, provide: `https://www.nationalreview.com/corner/you-too-can-be-a-mystic-or-at-least-get-to-know-god-and-his-great-love-for-you-better/`

This results in the following output:
```dir ./src/extractors/custom/www.nationalreview.com
fs.existsSync(dir) true
✔ Fetching fixture
(node:89925) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of null
    at Object.<anonymous> (/Users/REDACTED/Sites/mercury-parser/dist/generate-custom-parser.js:1476:43)
    at initialize.exports.each (/Users/REDACTED/Sites/mercury-parser/node_modules/cheerio/lib/api/traversing.js:300:24)
    at absolutizeSet$1 (/Users/REDACTED/Sites/mercury-parser/dist/generate-custom-parser.js:1467:27)
    at makeLinksAbsolute$$1 (/Users/REDACTED/Sites/mercury-parser/dist/generate-custom-parser.js:1495:3)
    at savePage (/Users/REDACTED/Sites/mercury-parser/dist/generate-custom-parser.js:6835:3)
    at /Users/REDACTED/Sites/mercury-parser/dist/generate-custom-parser.js:6760:14
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:89925) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:89925) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 8.05s.
```

## Detailed Description

This blocks the creation of a parser for content on nationalreview.com

## Possible Solution

Filter out srcsets with invalid values prior to processing (looking into what this entails now).

**Comment by Meandmybadself** [comment]
This _should_ be resolved by: https://github.com/postlight/mercury-parser/pull/386
